# Update action versions
- name: Set up Python
  uses: actions/setup-python@v5  # Updated version
  with:
    python-version: '3.11'  # Use newer Python

# Fix ImageMagick setup
- name: Install system dependencies
  run: |
    sudo apt-get update
    sudo apt-get install -y ffmpeg imagemagick
    # Better ImageMagick config
    sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.bak
    sudo tee /etc/ImageMagick-6/policy.xml > /dev/null <<EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE policymap [
      <!ELEMENT policymap (policy)+>
      <!ELEMENT policy (#PCDATA)>
      <!ATTLIST policy domain (delegate|coder|filter|path|resource) #IMPLIED>
      <!ATTLIST policy name CDATA #IMPLIED>
      <!ATTLIST policy pattern CDATA #IMPLIED>
      <!ATTLIST policy rights CDATA #IMPLIED>
      <!ATTLIST policy stealth (True|False) "False">
      <!ATTLIST policy value CDATA #IMPLIED>
    ]>
    <policymap>
      <policy domain="resource" name="memory" value="256MiB"/>
      <policy domain="resource" name="map" value="512MiB"/>
      <policy domain="resource" name="width" value="8KP"/>
      <policy domain="resource" name="height" value="8KP"/>
      <policy domain="resource" name="area" value="16KP"/>
      <policy domain="resource" name="disk" value="1GiB"/>
      <policy domain="coder" rights="read|write" pattern="*" />
    </policymap>
    EOF
